name: smart_shopping_app
description: Complete GetX Shopping App
publish_to: 'none' # এটা না থাকলে কোনো সমস্যা নেই, থাকলে ভালো

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_slidable: ^3.0.0
  iconsax: ^0.0.8
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google.png
